import { localePortableTextType, localeStringType, localeTextType } from './locale'
import {
  aboutSnippetBlock,
  chairmanMessageBlock,
  contactFormBlock,
  ctaBlock,
  featuredProjectBlock,
  heroVideoBlock,
  imageGridBlock,
  mapBlock,
  marqueeBlock,
  missionVisionBlock,
  numbersBlock,
  partnersBlock,
  projectsGridBlock,
  quoteBlock,
  bodyTextBlock,
  unitsBlock,
  whyMKNBlock,
} from './blocks'
import {
  contactSubmissionType,
  pageType,
  partnerType,
  projectType,
  siteFooterType,
  siteHeaderType,
  siteSettingsType,
} from './documents'

export const schemaTypes = [
  localeStringType,
  localeTextType,
  localePortableTextType,
  heroVideoBlock,
  bodyTextBlock,
  imageGridBlock,
  numbersBlock,
  marqueeBlock,
  featuredProjectBlock,
  partnersBlock,
  quoteBlock,
  ctaBlock,
  aboutSnippetBlock,
  projectsGridBlock,
  contactFormBlock,
  missionVisionBlock,
  whyMKNBlock,
  chairmanMessageBlock,
  unitsBlock,
  mapBlock,
  pageType,
  projectType,
  partnerType,
  contactSubmissionType,
  siteHeaderType,
  siteFooterType,
  siteSettingsType,
]
